apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstoreproductservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstoreproductservice
  template:
    metadata:
      labels:
        app: aks-petstoreproductservice
    spec:
      containers:
      - name: aks-petstoreproductservice
        image: celestinpetstore.azurecr.io/petstoreproductservice:latest
        ports:
        - containerPort: 80
        env:
          - name: PETSTOREPRODUCTSERVICE_SERVER_PORT
            value: "80"
          #- name: spring.config.name
           # value: application_with_everything_enabled
          #- name: APPLICATIONINSIGHTS_CONNECTION_STRING
         #   valueFrom:
            #  secretKeyRef:
              #  name: aisecretkey
              #  key: secret
