apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstorepetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstorepetservice
  template:
    metadata:
      labels:
        app: aks-petstorepetservice
    spec:
      containers:
      - name: aks-petstorepetservice
        image: celestinpetstore.azurecr.io/petstorepetservice:latest
        ports:
        - containerPort: 80
        env:
          - name: PETSTOREPETSERVICE_SERVER_PORT
            value: "80"
          - name: spring.config.name
            value: application_with_everything_enabled
         # - name: APPLICATIONINSIGHTS_CONNECTION_STRING
         #   valueFrom:
          #    secretKeyRef:
           #     name: aisecretkey
            #    key: secret
