apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstoreorderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstoreorderservice
  template:
    metadata:
      labels:
        app: aks-petstoreorderservice
    spec:
      containers:
      - name: aks-petstoreorderservice
        image: celestinpetstore.azurecr.io/petstoreorderservice:latest
       # resources:
       #   requests:
        #    cpu: 250m
         #   memory: 1Gi
          #limits:
           # cpu: 500m
            #memory: 2Gi
        ports:
        - containerPort: 80
        env:
          - name: PETSTOREORDERSERVICE_SERVER_PORT
            value: "80"
          - name: spring.config.name
            value: application_with_everything_enabled
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: aisecretkey
                key: secret
        #  - name: PETSTOREPRODUCTSERVICE_URL
         #   value: "http://aks-petstoreproductservice/"
       #   - name: PETSTOREORDERSERVICE_EMAIL_TOPIC_CONNECTION_STRING
          #  valueFrom:
          #    secretKeyRef:
           #     name: emailtopicconnstring
          #      key: secret
       #   - name: PETSTOREORDERSERVICE_SUBSCRIPTION_ID
      #      valueFrom:
          #    secretKeyRef:
        #        name: subscriptionid
           #     key: secret
